cat > app.env << EOF
PORT=5000
APP_ENV=development
MONGO_DB_NAME=Example
MONGO_DB_URL=http://127.0.0.1
REDIS_HOST=localhost
REDIS_PORT_AUTH=1234
REDIS_PORT_CHAT=4321
SALT=10
JWT_SECRET_ACCESS=asd
JWT_EXPIRY_ACCESS=1
JWT_SECRET_REFRESH=dsa
JWT_EXPIRY_REFRESH=2
AUTO_LOGOUT=4
AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672
EOF