version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    restart: on-failure
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo/.mongodb-tmp:/data/db
    networks:
      - chat

  redisAuth:
    image: redis:latest
    container_name: chat-redis-auth
    restart: on-failure
    ports:
      - ${REDIS_PORT_AUTH}:${REDIS_PORT_AUTH}
    volumes:
      - ./data/redis-auth:/data
    networks:
      - chat

  redisChat:
    image: redis:latest
    container_name: chat-redis
    restart: on-failure
    ports:
      - ${REDIS_PORT_CHAT}:${REDIS_PORT_CHAT}
    volumes:
      - ./data/redis-chat:/data
    networks:
      - chat

  rabbit:
    image: rabbitmq:latest
    container_name: chat-rabbitmq
    restart: on-failure
    ports:
      - 127.0.0.1:${AMQP_SERVER_PORT}:${AMQP_SERVER_PORT}
      - ${AMQP_CONSUMER_PORT}:${AMQP_CONSUMER_PORT}   # for sender and consumer connections
      - ${AMQP_SERVER_PORT}:${AMQP_SERVER_PORT} # for serve RabbitMQ GUI
    volumes:
      - ./data/rabbitmq/lib:/var/lib/rabbitmq
      - ./data/rabbitmq/log:/var/log/rabbitmq
    networks:
      - chat

  backend:
    build:
      context: ../noname-realtime-support-chat
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: on-failure
    depends_on:
      - mongodb
      - redisAuth
      - redisChat
      - rabbit
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./data/app:/app

    environment:
      - PORT=${PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_URL=mongodb://chat-mongodb:${MONGO_PORT}/${MONGO_DB_NAME}
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
      - JWT_EXPIRY_ACCESS=${JWT_EXPIRY_ACCESS}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - JWT_EXPIRY_REFRESH=${JWT_EXPIRY_REFRESH}
      - AUTO_LOGOUT=${AUTO_LOGOUT}
      - SALT=${SALT}
      - REDIS_HOST=chat-redis-auth
      - REDIS_PORT=${REDIS_PORT}
      - AMQP_SERVER_URL=amqp://guest:guest@chat-rabbitmq:5672
    networks:
      - chat

networks:
  chat:
    driver: bridge