version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    restart: on-failure
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - ./data/mongo/.mongodb-tmp:/data/db
    networks:
      - chat

  redis:
    image: redis:latest
    container_name: chat-redis
    restart: on-failure
    command:
      - --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./data/redis-chat:/data
    networks:
      - chat

  backend:
    build:
      context: ../realtime-support-chat
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: on-failure
    depends_on:
      - mongodb
      - redis
    ports:
      - ${APP_PORT}:${APP_PORT}
#    volumes:
#      - ./data/app:/build

    environment:
      - PORT=${APP_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_URL=mongodb://chat-mongodb:${MONGO_PORT}/${MONGO_DB_NAME}
      - REDIS_HOST=chat-redis-auth
      - REDIS_PORT=${REDIS_PORT_AUTH}
    networks:
      - chat

networks:
  chat:
    driver: bridge