name: development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server
        run: make build

  linter:
    runs-on: ubuntu-latest
    name: Run linter
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        run: make lint

  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs:
      - linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          chmod +x app.test.env.sh
          ./app.test.env.sh
          make test